name: Javascript Testing Framework
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    container: cypress/browsers:node18.12.0-chrome106-ff106
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Copy catalog fixture data for schools
        uses: canastro/copy-file-action@ae66602ce7d214dbd2e298c1db67a81388755a0a
        with:
          source: "./cypress/fixtures/schools.json"
          target: "./data/schools.json"

      - name: Copy catalog fixture data for courses
        uses: canastro/copy-file-action@ae66602ce7d214dbd2e298c1db67a81388755a0a
        with:
          source: "./cypress/fixtures/courses.json"
          target: "./data/courses.json"

      - name: Copy catalog fixture data for school_categories
        uses: canastro/copy-file-action@ae66602ce7d214dbd2e298c1db67a81388755a0a
        with:
          source: "./cypress/fixtures/school_categories.json"
          target: "./data/school_categories.json"

      - name: Copy catalog fixture data for credit_types
        uses: canastro/copy-file-action@ae66602ce7d214dbd2e298c1db67a81388755a0a
        with:
          source: "./cypress/fixtures/credit_types.json"
          target: "./data/credit_types.json"

      - name: Cypress run tests
        uses: cypress-io/github-action@v4
        with:
          build: npm run export
          start: npm run start
          wait-on: 'http://localhost:3000'
          config: baseUrl=http://localhost:3000
